name: CMake - Google Tests

on:
  push:
    branches: [ run-tests ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ # or clang if you prefer

      - name: Configure CMake
        run: |
          cmake -S . -B build \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run Google Tests
        run: |
          # Option 1: run the test binary directly
          ./build/googletest/Google_Tests_run\
            --gtest_output=xml:./build/test-results/gtest-results.xml

          # Option 2 (if you add enable_testing()/add_test() in CMake): use ctest
          # ctest --test-dir build --output-on-failure

      - name: Upload test results
        if: always()  # still upload if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: gtest-results
          path: build/test-results

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Google Tests
          path: build/test-results/**/*.xml
          reporter: jest-junit   # JUnit-compatible parser